export const comunasPorRegion: Record<string, string[]> = {
  "Arica y Parinacota": ["Arica", "Camarones", "Putre", "General Lagos"],
  Tarapacá: [
    "Iquique",
    "Alto Hospicio",
    "Camiña",
    "Colchane",
    "Huara",
    "Pica",
    "Pozo Almonte",
  ],
  Antofagasta: [
    "Antofagasta",
    "Mejillones",
    "María Elena",
    "Calama",
    "Ollagüe",
    "San Pedro de Atacama",
    "Tocopilla",
    "Sierra Gorda",
    "Taltal",
  ],
  Atacama: [
    "Copiapó",
    "Caldera",
    "Tierra Amarilla",
    "Chañaral",
    "Diego de Almagro",
    "Vallenar",
    "Alto del Carmen",
    "Freirina",
    "Huasco",
  ],
  Coquimbo: [
    "La Serena",
    "Coquimbo",
    "Andacollo",
    "La Higuera",
    "Paihuano",
    "Vicuña",
    "Ovalle",
    "Río Hurtado",
    "Monte Patria",
    "Combarbalá",
    "Punitaqui",
    "Illapel",
    "Los Vilos",
    "Salamanca",
  ],
  Valparaíso: [
    "Valparaíso",
    "Viña del Mar",
    "Quilpué",
    "Villa Alemana",
    "San Antonio",
    "Cartagena",
    "El Quisco",
    "El Tabo",
    "Algarrobo",
    "Casablanca",
    "Concón",
    "Papudo",
    "Petorca",
    "La Ligua",
    "Zapallar",
    "Puchuncaví",
    "Quintero",
    "Calle Larga",
    "Llay Llay",
    "Los Andes",
    "Rinconada",
    "San Felipe",
    "Putaendo",
    "Santa María",
    "Panquehue",
    "Catemu",
    "Cabildo",
    "Papudo",
    "Quintero",
  ],
  "Metropolitana de Santiago": [
    "Santiago",
    "Puente Alto",
    "Maipú",
    "La Florida",
    "Las Condes",
    "Providencia",
    "Ñuñoa",
    "Macul",
    "Vitacura",
    "La Reina",
    "San Bernardo",
    "Peñalolén",
    "Pudahuel",
    "Recoleta",
    "Cerrillos",
    "Independencia",
    "San Joaquín",
    "San Miguel",
    "San Ramón",
    "La Cisterna",
    "El Bosque",
    "Estación Central",
    "Huechuraba",
    "Conchalí",
    "Renca",
    "Lo Prado",
    "Quilicura",
    "Lo Barnechea",
    "La Granja",
    "Lo Espejo",
    "Buin",
    "Paine",
    "Isla de Maipo",
    "Pedro Aguirre Cerda",
    "Talagante",
    "Padre Hurtado",
    "Melipilla",
    "María Pinto",
    "Curacaví",
    "Alhué",
    "San Pedro",
  ],
  "Libertador General Bernardo O'Higgins": [
    "Rancagua",
    "Machalí",
    "Requínoa",
    "Graneros",
    "Olivar",
    "Codegua",
    "Malloa",
    "Pichidegua",
    "Peumo",
    "Coltauco",
    "Doñihue",
    "Quinta de Tilcoco",
    "San Vicente",
    "Santa Cruz",
    "Lolol",
    "Pichilemu",
    "Cachapoal",
    "Colchagua",
    "Cardenal Caro",
  ],
  Maule: [
    "Talca",
    "Curicó",
    "Linares",
    "Constitución",
    "Río Claro",
    "San Clemente",
    "Maule",
    "Empedrado",
    "Pencahue",
    "Licantén",
    "Teno",
    "Romeral",
    "Sagrada Familia",
    "Hualañé",
    "Vichuquén",
    "Villa Alegre",
    "San Javier",
    "Retiro",
    "Parral",
  ],
  Ñuble: [
    "Chillán",
    "Chillán Viejo",
    "Pemuco",
    "Quirihue",
    "Ránquil",
    "Bulnes",
    "Cobquecura",
    "Coelemu",
    "Ninhue",
    "Ñiquén",
    "El Carmen",
    "Pinto",
    "Quillón",
    "San Ignacio",
    "San Nicolás",
    "Yungay",
    "Trehuaco",
  ],
  Biobío: [
    "Concepción",
    "Los Ángeles",
    "Talcahuano",
    "Penco",
    "Tomé",
    "Florida",
    "Hualpén",
    "Hualqui",
    "Santa Juana",
    "Lota",
    "Coronel",
    "San Pedro de la Paz",
    "Chiguayante",
    "Cabrero",
    "Tucapel",
    "Negrete",
    "Nacimiento",
    "Mulchén",
    "Quilleco",
    "Yumbel",
    "Alto Biobío",
    "Quirihue",
    "Coihueco",
    "San Rosendo",
  ],
  "La Araucanía": [
    "Temuco",
    "Padre Las Casas",
    "Villarrica",
    "Pucón",
    "Lautaro",
    "Angol",
    "Carahue",
    "Collipulli",
    "Curacautín",
    "Gorbea",
    "Nueva Imperial",
    "Freire",
    "Toltén",
    "Teodoro Schmidt",
    "Victoria",
    "Melipeuco",
  ],
  "Los Ríos": [
    "Valdivia",
    "Lanco",
    "Máfil",
    "Mariquina",
    "Paillaco",
    "Panguipulli",
    "La Unión",
    "Futrono",
    "Lago Ranco",
    "Río Bueno",
  ],
  "Los Lagos": [
    "Puerto Montt",
    "Puerto Varas",
    "Osorno",
    "Puyehue",
    "Cochamó",
    "San Pablo",
    "Llanquihue",
    "Chiloé",
    "Calbuco",
    "Frutillar",
    "Maullín",
    "Ancud",
    "Quemchi",
    "Dalcahue",
    "Curaco de Vélez",
    "Quinchao",
    "Puqueldón",
    "Chonchi",
    "Queilén",
    "Quellón",
    "Fresia",
    "Los Muermos",
    "Puerto Octay",
    "Palena",
  ],
  "Aysén del General Carlos Ibáñez del Campo": [
    "Coyhaique",
    "Aysén",
    "Cisnes",
    "Guaitecas",
    "Chile Chico",
    "Río Ibáñez",
    "Cochrane",
    "O'Higgins",
    "Tortel",
    "Capitán Prat",
  ],
  "Magallanes y de la Antártica Chilena": [
    "Punta Arenas",
    "Porvenir",
    "Natales",
    "Torres del Paine",
    "Primavera",
    "Timaukel",
    "Río Verde",
    "Laguna Blanca",
    "San Gregorio",
    "Antártica",
  ],
};
